#! /usr/bin/env bash

stow=@stow@
out=@out@

set -u

pkgs=(
    git
)

for pkg in "${pkgs[@]}"
do
    stow --stow \
         --dir="$out/stow" \
         --target="$HOME" \
         $@ \
         "$pkg"
done
