keys:
  - &ivan age12rrd4cu3xjc4wue5yul8752782lhac5rtxpt65ez5k8xwc7yd5ds6wypa2
  - &thinkpad9 age12wlz6sa2e7lgwrdk8dljvhjlazc5536dgpsmy8eyvtlvqttewp6qzsp699
creation_rules:
  - path_regex: sops-nix/secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *ivan
      - *thinkpad9
