#! /usr/bin/env bash

set -eu

tmpDir=$(mktemp --tmpdir -d sumall-cli.XXXXXX)
dstDir=/etc/nixos/overlays/sumall/sumall-cli

main() {
    make_workspace
    package_dependencies
    package_sumall_cli

    if check_build
    then
        apply_update
    else
        report_failure
    fi
}

make_workspace() {
    printf '%sMaking temporary workspace%s\n' $(tput bold) $(tput sgr0)

    nix-shell --packages git --run \
        "git clone --depth 1 git@github.com:SumAll/sumall-cli.git $tmpDir"

    pushd $tmpDir
}

package_dependencies() {
    printf '%sPackaging dependencies%s\n' $(tput bold) $(tput sgr0)

    nix-shell --packages pypi2nix --run \
        'pypi2nix -V "2.7" -r requirements.txt -E libffi -E openssl'
}

package_sumall_cli() {
    printf '%sPackaging sumall-cli%s\n' $(tput bold) $(tput sgr0)

    # copy existing components
    cp $dstDir/{default,nixpkgs,requirements_override,version}.nix $tmpDir/
    cp $dstDir/{update-nixpkgs,update-sumall-cli}.sh $tmpDir/

    local version
    version=$(grep -oP '__version__ = "\K[^"]+' $tmpDir/sumall/__init__.py)

    # update revisions
    $tmpDir/update-sumall-cli.sh "$tmpDir" "$version"
    $tmpDir/update-nixpkgs.sh
}

check_build() {
    printf '%sRunning test build%s\n' $(tput bold) $(tput sgr0)

    nix-build --no-out-link $tmpDir
}

apply_update() {
    for x in {nixpkgs,requirements,version}.nix
    do
        cp --force $tmpDir/$x $dstDir/
    done

    popd >/dev/null && rm --recursive --force $tmpDir

    printf '\n%s%s✓%s %sDone%s\n' \
        $(tput bold) $(tput setaf 2) $(tput sgr0) \
        $(tput bold) $(tput sgr0)

    exit 0
}

report_failure() {
    printf '\n%s%s✗%s %sBuild Failed%s\n' \
        $(tput bold) $(tput setaf 1) $(tput sgr0) \
        $(tput bold) $(tput sgr0)

    echo "Workspace: $PWD"
    exit 1
}

main
