#! /usr/bin/env bash

abduco=@abduco@
awk=@awk@
dmenu=@dmenu@
sort=@sort@

set -u

$abduco                                           \
    | $awk -F '\t' 'NR>1 && !/^\*/ { print $NF }' \
    | $sort                                       \
    | $dmenu "$@"
