#! /usr/bin/env bash

abduco=@abduco@
alacritty=@alacritty@
basename=@basename@
cat=@cat@
dirname=@dirname@
setsid=@setsid@

set -u

usage() {
    $cat >&2 <<EOF
Usage: ${0##*/} ARG...
e.g.
  ${0##*/} nvim
EOF
}

(( $# == 0 )) && { usage ; exit 1 ; }

: ${NAME:=$($basename "$PWD") $1}

exec $alacritty --command $abduco -A "$NAME" "$@" &
