#! /usr/bin/env bash

diss=@diss@
dmenu_diss=@dmenu_diss@

set -u

# I commonly call dmenu_diss after detaching from a diss session within neovim.
# Since neovim turns on focus reporting and is unaware of the disconnect, the
# terminal will receive a Focus Lost event upon launching dmenu, and a Focus
# Gained event when dmenu exits. These events manifest as control sequences
# (^[[O and ^[[I) that are printed to the terminal's output. To prevent this,
# make sure focus reporting is turned off before we invoke dmenu.
echo -ne '\e[?1004l'

session=$($dmenu_diss "$@")

[ -n "$session" ] || exit 1

exec $diss -a "$session" &
