#! /usr/bin/env bash

cat=@cat@
cut=@cut@
dmenu=@dmenu@
display=@display@
fc_list=@fc_list@
grep=@grep@
sort=@sort@
xargs=@xargs@

set -u

usage() {
    $cat >&2 <<EOF
Usage: $0 [dmenu-options]
e.g.
  ${0##*/}
  ${0##*/} -i -l 24
EOF
}

if (( $# == 1 )) && [[ "$1" = "-h" || "$1" = "--help" ]]
then
    usage
    exit 1
fi

$fc_list                \
    | $cut -d: -f1      \
    | $grep '\.[ot]tf$' \
    | $sort --unique    \
    | $dmenu "$@"       \
    | $xargs --no-run-if-empty $display
