#! /usr/bin/env bash

dmenu=@dmenu@
ls=@ls@
manpath=@manpath@
perl=@perl@
sort=@sort@

set -eu

paths=$($manpath --quiet)

for d in ${paths//:/ }
do
    for s in man{1..9}
    do
        dir="${d}/${s}"
        if [ -d "$dir" ]
        then
            $ls -A "$dir" | $perl -n -e '
                /(.*?)(?:\.[^.]+)?\.(?:gz|bz2)$/
                && print "$1\n"
            '
        fi
    done
done | $sort --unique | $dmenu "$@"
