#!/usr/bin/env bash

set -eu

# https://github.com/thesofproject/sof/issues/5168

# remove and re-insert problematic kernel module
sudo remod-sof || true

# restart pulseaudio
systemctl restart --user pulseaudio.service

# restart xmonad
xdotool key super+q
