local autoload = require('ncore.autoload')
ncore = autoload('ncore')

require('ncore.options')
require('ncore.keymap')
require('ncore.hydra')
require('ncore.statusline')
require('ncore.tabline')
require('ncore.tabstack')
require('ncore.hint')
require('ncore.telescope')
require('ncore.gui')
require('ncore.align')
